name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call-reusable-workflow:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: cr2007/actions/.github/workflows/gh-pages-deploy.yml@v1
    with:
      build-command: bun run build
      output-dir: dist
